### ISSUE TITLE
need better readme for installation

### ISSUE THREAD

**Issue by rsoorajs** [abdimk/babylon#1]
where should i add `telegram bot token `?

**Comment by abdimk** [comment]
https://github.com/abdimk/babylon/blob/master/Read%20this%20before%20doing%20any%20thing.txt

**Comment by abdimk** [comment]
Put it on Babylon. Py file then run it using python anywhere server or your PC for that you need to remove the server configuration you will find it on the upper part from 11 - 23

**Comment by rsoorajs** [comment]
Thanks
